name: main
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
         node-version: '14'
      - run: df -h
      - run: npm install
      - run: df -h
